name: CI

on:
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 22
        
    - name: Install backend dependencies
      run: |
        npm install

    - name: Run backend tests
      run: |
        npm test
    
    - name: Install frontend dependencies
      run: |
        cd ai-testgen-frontend
        npm install
    
    - name: Build frontend
      run: |
        cd ai-testgen-frontend
        npm test
        
       